QA-15101 Remove manual registration of JCR Event listeners.
Jahia/OSGi-modules-samples pull request #35
Opened 2024-06-18 09:14 UTC by jayblanc

## JIRA

https://jira.jahia.org/browse/QA-15101

## Description

Upgrade samples to the latest module parent
Due to modifications in the way JCREventListener are registered, there is no more need to do it manually.

## Tests

The following are included in this PR
- [ ] Unit Tests (Most changes _should_ have unit tests)
- [ ] Integration Tests

## Checklist

I have considered the following implications of my change: 

- [X] Security (in particular for changes to authentication, authorization, data fetching, ...)
- [X] Performance
- [X] Migration
- [X] Code maintainability

## Documentation

- [ ] Inline documentation
- [ ] Internal Documentation (wiki)
- [ ] User-facing Documentation

2024-06-24 05:50 UTC, dgriffon requested changes
As a sample code, it would be better to have as a parent module the released version of Jahia

2024-06-24 05:50 UTC, dgriffon commented on servlet-filter-samples/pom.xml
> -        <version>8.0.0.0</version>
You need `<relativePath/>` as for other modules

2024-06-24 05:50 UTC, dgriffon commented on login-provider/pom.xml
> -        <relativePath />
You need `<relativePath/>` as for other modules

2024-06-26 07:27 UTC, jayblanc commented
replaced by https://github.com/Jahia/OSGi-modules-samples/pull/36

2024-06-26 07:27 UTC, closed without merging